//Timer
export const TIMER_SET_HOUR = 'TIMER_SET_HOUR';
export const TIMER_SET_MIN = 'TIMER_SET_MIN';
export const TIMER_SET_SEC = 'TIMER_SET_SEC';
export const TIMER_SET_ZERO = 'TIMER_SET_ZERO';
export const TIMER_SHOW_SELECT = 'TIMER_SHOW_SELECT';
export const TIMER_HIDE_SELECT = 'TIMER_HIDE_SELECT';
export const TIMER_SET_INFO = 'TIMER_SET_INFO';
export const TIMER_ACTIVE_SIGNAL = 'TIMER_ACTIVE_SIGNAL';
export const TIMER_STOP_SIGNAL = 'TIMER_STOP_SIGNAL';
export const TIMER_RUNNING = 'TIMER_RUNNING';

//Stopwatch
export const STOPWATCH_RUNNING = 'STOPWATCH_RUNNING';
export const STOPWATCH_SET_HOUR = 'STOPWATCH_SET_HOUR';
export const STOPWATCH_SET_MIN = 'STOPWATCH_SET_MIN';
export const STOPWATCH_SET_SEC = 'STOPWATCH_SET_SEC';
export const STOPWATCH_SET_MS = 'STOPWATCH_SET_MS';
export const STOPWATCH_SET_DATE = 'STOPWATCH_SET_DATE';
export const STOPWATCH_SET_STOP_TIME = 'STOPWATCH_SET_STOP_TIME';
export const STOPWATCH_ZERO = 'STOPWATCH_ZERO';
export const STOPWATCH_INFO = 'STOPWATCH_INFO';
export const STOPWATCH_PRINT_TIME = 'STOPWATCH_PRINT_TIME';

//Pomidoro
export const POMIDORO_INCREMENT = 'POMIDORO_INCREMENT';
export const POMIDORO_DECREMENT = 'POMIDORO_DECREMENT';
export const POMIDORO_SET_WORK_MIN = 'POMIDORO_SET_WORK_MIN';
export const POMIDORO_SET_WORK_SEC = 'POMIDORO_SET_WORK_SEC';
export const POMIDORO_SET_RELAX_MIN = 'POMIDORO_SET_RELAX_MIN';
export const POMIDORO_SET_RELAX_SEC = 'POMIDORO_SET_RELAX_SEC';
export const POMIDORO_START = 'POMIDORO_START';
export const POMIDORO_STOP = 'POMIDORO_STOP';
export const POMIDORO_COPY = 'POMIDORO_COPY';
export const POMIDORO_RESET = 'POMIDORO_RESET';
export const POMIDORO_STATUS = 'POMIDORO_STATUS';
export const POMIDORO_SET_INFO = 'POMIDORO_SET_INFO';

//ChessClock
export const CHESSCLOCK_INCREMENT = 'CHESSCLOCK_INCREMENT';
export const CHESSCLOCK_DECREMENT = 'CHESSCLOCK_DECREMENT';
export const CHESSCLOCK_TIME_COPY = 'CHESSCLOCK_TIME_COPY';
export const CHESSCLOCK_TIME_RESET = 'CHESSCLOCK_TIME_RESET';
export const CHESSCLOCK_ACTIVE_RESET = 'CHESSCLOCK_ACTIVE_RESET';
export const CHESSCLOCK_ACTIVE_STATUS = 'CHESSCLOCK_ACTIVE_STATUS';
export const CHESSCLOCK_ACTIVE_UNMOUNT = 'CHESSCLOCK_ACTIVE_UNMOUNT';
export const CHESSCLOCK_SET_MIN = 'CHESSCLOCK_SET_MIN';
export const CHESSCLOCK_SET_SEC = 'CHESSCLOCK_SET_SEC';
export const CHESSCLOCK_SET_ACTIVE_PLAYER = 'CHESSCLOCK_SET_ACTIVE_PLAYER';
export const CHESSCLOCK_SET_INFO = 'CHESSCLOCK_SET_INFO';
export const CHESSCLOCK_ACTIVE_SIGNAL = 'CHESSCLOCK_ACTIVE_SIGNAL';
export const CHESSCLOCK_STOP_SIGNAL = 'CHESSCLOCK_STOP_SIGNAL';

//ALARM
export const ALARM_GET_LOCAL_ALARM = 'ALARM_GET_LOCAL_ALARM';
export const ALARM_SET_TIME = 'ALARM_SET_TIME';
export const ALARM_CURRENT_TIME = 'ALARM_CURRENT_TIME';
export const ALARM_TOGGLE_MODAL = 'ALARM_TOGGLE_MODAL';
export const ALARM_INCREMENT = 'ALARM_INCREMENT';
export const ALARM_DECREMENT = 'ALARM_DECREMENT';
export const ALARM_ADD_ALARM = 'ALARM_ADD_ALARM';
export const ALARM_DELETE_ALARM = 'ALARM_DELETE_ALARM';
export const ALARM_STOP_SIGNAL = 'ALARM_STOP_SIGNAL';
export const ALARM_EDIT_SIGNAL = 'ALARM_EDIT_SIGNAL';
export const ALARM_EDIT_INCREMENT = 'ALARM_EDIT_INCREMENT';
export const ALARM_EDIT_DECREMENT = 'ALARM_EDIT_DECREMENT';
export const ALARM_SAVE_ALARM = 'ALARM_SAVE_ALARM';

